#!/bin/bash

echo "==================================================================="
echo "Push ViralTracker to GitHub"
echo "==================================================================="
echo ""
echo "Option 1: Create new repo with GitHub CLI"
echo "-------------------------------------------------------------------"
echo "gh repo create viraltracker --private --source=. --remote=origin"
echo "git push -u origin master"
echo ""
echo "Option 2: Add existing repo as remote"
echo "-------------------------------------------------------------------"
echo "git remote add origin https://github.com/YOUR_USERNAME/viraltracker.git"
echo "git push -u origin master"
echo ""
echo "==================================================================="
echo "After pushing, you're ready for Phase 3!"
echo "==================================================================="
