"""Shared consumer-awareness rubric — Eugene Schwartz's 5 stages of awareness
(Breakthrough Advertising, 1966) refined with modern direct-response practice.

Single source of truth injected into the ad-creative classification prompts so the
awareness buckets are consistent across creative types. Consumers: the video deep-
analysis + legacy video prompts (video_analysis_service), the static image classifier
(image_analysis_service, with STATIC_AWARENESS_TELLS), the ads copy classifier
(ad_intelligence/classifier_service), and the template classifier
(template_queue_service, with STATIC_AWARENESS_TELLS, tripwire-pinned). Any edit to
AWARENESS_RUBRIC or STATIC_AWARENESS_TELLS must ride the consuming prompts' version
bumps — the template tripwire test enforces this.

Synthesized + adversarially verified 2026-06-05 (3-researcher panel -> synthesis ->
red-team), hardened by an independent Codex research + adversarial review (which
corrected an over-broad "cold brand/category mention = solution_aware" rule toward
Schwartz's true desire/result-aware stage 3), and live-calibrated against Martin
video classifications. Core principle: classify by the knowledge state the ad's
OPENING *presumes*, not what it merely mentions.

Contains no curly braces, so it is safe to pass as a ``.format`` substitution value.
"""

AWARENESS_RUBRIC = """Awareness = what the PROSPECT already knows. Classify by the knowledge state the opening PRESUMES (treats as given), NOT what it merely mentions. Naming a brand, category, or mechanism does NOT raise the stage if the ad is still INTRODUCING it cold. If the ad must teach a thing, the viewer is on the LOWER side of that seam.

The 5 stages (cold to hot):
- unaware - Knows nothing relevant; the opening presumes NO felt problem. Tells: pure curiosity/story/identity or surprising-fact/contrarian leads with NO specific symptom or pain the viewer would recognize in themselves. A personal STORY that enumerates specific recognizable symptoms is problem_aware, not unaware - judge the substance, not the narrative framing.
- problem_aware - Feels or recognizes the pain/need, but the opening does not presume prior knowledge of a solution path. Tells: symptom/audience callouts and problem agitation. It may mention a category/mechanism only if it is clearly teaching it cold, not relying on prior familiarity.
- solution_aware - Knows or immediately recognizes the desired result/solution path, but does NOT yet know that this product is the answer. Tells: desired-outcome leads, known-category comparisons ("not a sleep pill"), "tried everything" claims, alternatives, demos, or mechanisms presented as the way to get the desired result. A cold brand mention alone is NOT enough.
- product_aware - Presumes you already know YOUR product; deciding if it's best. Tells: brand-vs-named-rival comparison ("switched from X"), "you've seen us everywhere", objection-handling on this product, a NEW/IMPROVED announcement about the named product ("new formula", "now 2x absorption", "we fixed the taste") that presumes familiarity with the product's prior state (self-comparison against the product's own past is product-level work even with no rival or testimonial), OR an opening that goes STRAIGHT into reviewing/endorsing the specific named product (testimonial-first, "why I love [Brand]") with features/mechanism used as proof of THIS product's superiority and NO category/problem bridge.
- most_aware - Already wants it; needs a reason to act now. Tells: the LEAD is the deal/terms (price, discount, urgency, code, "back in stock"), presuming desire is settled.

Boundary tests (one decidable question each; tie -> pick the LOWER side):
- unaware vs problem_aware: Does the opening presume a problem the viewer ALREADY feels? Merely surfacing one = unaware; presuming felt pain = problem_aware.
- problem_aware vs solution_aware: Does the opening rely on the viewer already wanting a result, knowing a solution path/category, having tried alternatives, or understanding a mechanism as a MEANS to the result? Yes = solution_aware. A mechanism explained as the ROOT CAUSE of the problem (no fix offered yet) stays problem_aware. Mere cold introduction of a brand/category/mechanism does not raise the stage.
- solution_aware vs product_aware: Does the opening do any BRIDGE/introduction work - presenting the product as the answer to a desired result/category? Bridging/introducing it = solution_aware. If it SKIPS the bridge and opens straight into reviewing/endorsing the NAMED product (social proof + proof of its superiority), presuming you are already evaluating it = product_aware.
- product_aware vs most_aware: Is the LEAD an actual OFFER/deal (price, discount, urgency, scarcity) presuming desire is settled? Yes = most_aware. A hard CTA ("click the link") or a results-timeline that still sells on the product's MERIT/claims is product_aware, not most_aware. A risk-reversal lead (money-back guarantee, free trial) is objection-handling on the product = product_aware, not most_aware — it speaks to someone still hesitating about the product, not someone whose desire is settled.

Skip pure attention-grabs ("STOP SCROLLING!") and judge the substantive message. Do NOT conflate awareness with market sophistication: unique mechanisms, enlarged claims, and identity hooks are sophistication/proof/angle devices — they never RAISE the stage by themselves. They affect awareness only when the creative presumes the viewer already understands the problem, result, category, or product; an ad that is ONLY identity/curiosity, presuming none of those, stays unaware.

A testimonial/review does NOT set the stage by itself - the CONTENT does. For a testimonial opening, judge the focus of the first ~10s: pain/symptoms/emotional struggle only, no fix named ("so exhausted I couldn't even play with my kids") = problem_aware; a general category, ingredient, or lifestyle change, NOT your brand ("once I started taking pine bark extract, my brain fog cleared") = solution_aware; the specific BRAND named as what they took, presuming you know it ("I just started taking Navitol and my energy is back") = product_aware.

Worked examples (opening unless noted):
- "Cortisol Reducer NOT a sleep pill" over a 3:13 AM clock -> solution_aware (positions against a known category + presents the mechanism as the MEANS; the problem visual does not lower it).
- "Your cortisol is up, you don't sleep; you don't sleep, your cortisol's up - a vicious cycle" (names the SAME mechanism but as the ROOT CAUSE, no fix offered) -> problem_aware (root-cause education deepens problem-awareness; mechanism-as-cause is not mechanism-as-means).
- Opens on a customer testimonial of the named brand ("Wow, I started taking Navitol and my energy improved") + "one thing I love about Navitol..." + mechanism (blood-brain barrier) used as proof of its superiority, with NO category/problem bridge -> product_aware (review/endorsement posture presumes the viewer is already evaluating the named product; classic retargeting copy). Contrast: a brand named while still BRIDGING from a desired result ("tired? there's a better way, it's called X") would be solution_aware.
- "My wife got very unwell - exhausted, brain fog, trouble sleeping" (a personal story enumerating specific recognizable symptoms) -> problem_aware (symptom callout presumes a felt problem; the story framing does not make it unaware).
- "Always tired moms... STOP SCROLLING!" -> skip the grab; classify the first substantive line ("always tired moms" = problem_aware).
- ENDING example: shows the branded bottle, lists the product's specific benefits + proof, with a "click the link" CTA and a results timeline but NO discount/urgency/deal -> product_aware (selling on the product's MERIT), NOT most_aware (which LEADS with the offer/deal)."""


# ---------------------------------------------------------------------------
# Shared awareness VOCABULARY — the one-definition home.
# Every consumer (ads image/video classifiers, the TEMPLATE classifier, scorers,
# UI labels) derives from these constants. Do NOT define a second copy anywhere:
# duplicated vocabularies are exactly the drift this module exists to prevent.
# ---------------------------------------------------------------------------

# Canonical enum order: least-aware -> most-aware. The INDEX+1 is the canonical
# 1-5 ordinal used wherever awareness is stored/compared as an INT
# (scraped_templates.awareness_level, SelectionContext.awareness_stage).
AWARENESS_LEVELS_ORDERED = (
    "unaware", "problem_aware", "solution_aware", "product_aware", "most_aware",
)

# The ONLY values allowed by the awareness CHECK constraints
# (ad_image_analysis.awareness_level, ad_creative_classifications.*_awareness_level).
VALID_AWARENESS_LEVELS = frozenset(AWARENESS_LEVELS_ORDERED)

# enum <-> INT ordinal (lossless both ways; locked by a tripwire test).
AWARENESS_LEVEL_ORDER = {lvl: i + 1 for i, lvl in enumerate(AWARENESS_LEVELS_ORDERED)}
AWARENESS_INT_TO_LEVEL = {i + 1: lvl for i, lvl in enumerate(AWARENESS_LEVELS_ORDERED)}

# INT -> human display label ("Problem Aware") — drives all UI labels/badges.
AWARENESS_LEVEL_LABELS = {
    i + 1: lvl.replace("_", " ").title() for i, lvl in enumerate(AWARENESS_LEVELS_ORDERED)
}


def normalize_awareness_level(value):
    """Lower/strip/space->underscore an awareness label; return None if not canonical.

    The trust-boundary normalizer for ALL Gemini-returned awareness labels: recovers
    casing/spacing variants ("Product Aware" -> product_aware), nulls true garbage so
    off-rubric output degrades to None instead of violating a DB CHECK constraint.
    """
    if not value or not isinstance(value, str):
        return None
    norm = value.strip().lower().replace(" ", "_")
    return norm if norm in VALID_AWARENESS_LEVELS else None


# The STATIC-image sub-rules layered on top of the core rubric — how to weigh
# VISUALS against text in a single frame (bottle-as-hero decisive, subordinate
# pack-shots don't raise the stage, blind hooks, testimonial routing, etc.).
# Hand-calibrated on the ads golden set; shared verbatim by BOTH static
# classifiers (ads images + scraped templates) so a creative is graded the same
# wherever it appears. Brace-free (safe inside .format templates). Covered by
# the template tripwire pin together with AWARENESS_RUBRIC.
STATIC_AWARENESS_TELLS = """Static-format tells. Apply in ORDER: (1) the dominance gates decide which elements COUNT (identifiable hero/co-hero product vs corner signature; banner-scale offer vs badge; lead-scale proof vs trust furniture; headline/lead vs body); (2) a counted banner-scale OFFER = most_aware; (3) a counted hero branded product sets the solution_aware FLOOR; (4) counted product-level work in the dominant message raises to product_aware; (5) otherwise route by the dominant message's content. Ties -> the LOWER stage.

- PROMINENT BRANDED PRODUCT (decisive floor): when a branded product shot is the visual hero or co-hero (the bottle/pack is a primary subject, with a brand name or logo visible), the ad is AT LEAST solution_aware — never problem_aware or unaware — EVEN IF the headline is a problem hook ("Feeling tired?", "IBS?"), a solution mechanism ("reduce cortisol", "not a sleep pill"), or an educational listicle ("7 Reasons... this supplement"). Showing the specific branded bottle ties the problem/mechanism directly to THIS product instead of teaching the category. Whether it rises to product_aware depends on PRODUCT-LEVEL WORK in the DOMINANT message: differentiation/USP framing (incl. "old way vs new way" stories that argue the visible product's SUPERIORITY over alternatives — an origin story merely explaining why it exists is bridge work, see AUTHORITY vs DEFENSE), objection-handling, a review/testimonial that endorses the named product or its result from an EVALUATION posture (a discovery-framed recommendation stays bridge work — see the testimonial rule), lead-scale aggregate proof (see PROOF PROMINENCE), specific superiority claims, comparison vs rivals, a listicle/"This [product]" reference, or ANY content presuming the viewer is already choosing or using THIS product (a personalization quiz like "find YOUR [Brand] formula", dosage/usage instructions as the lead, subscribe-and-save framing). WITH such content = product_aware (the content presumes you are evaluating THIS product). WITHOUT any product-level work — the hero product simply introduced as the answer to the problem/result — it is the classic BRIDGE = solution_aware (the ad is telling you the product exists, not defending it). Scan the WHOLE frame for the product: this rule triggers even when the branded bottle/pack sits ALONGSIDE a cartoon, before/after panels, or a lifestyle scene at co-hero scale. (Still not most_aware unless a counted banner-scale offer is present — see OFFER PROMINENCE.) PROMINENT means the product is a primary subject: the label/brand is readable at feed size AND the pack is what the eye lands on first, occupies roughly 15%+ of the frame, or is among the first two elements in reading order. A SMALL pack-shot (roughly 1/8 of the frame or less, corner/footer placement, or not among the first two visual elements) beneath a DOMINANT problem/symptom/outcome message is a brand signature, not the message — it does NOT trigger the floor; judge by the dominant message. "Alongside" above means co-hero scale (the bottle shares the stage), not a corner signature. The product must also be IDENTIFIABLE at a glance — a clearly readable label/brand on the pack itself, deliberately displayed as a subject of the frame. A generic-looking container or drink held as a lifestyle PROP (branding faint or illegible at feed size), where the brand is established only by a footer logo or page name, is NOT a prominent branded product shot — judge by the dominant message.
- PROOF PROMINENCE (mirrors offer prominence): product-level work counts only when it is part of the DOMINANT message — headline/sub-headline scale, legible at feed size. Badge-scale trust furniture — a star-rating + review-count strip, press/"as seen in" logo rows, small award or credential seals ("Doctor-formulated" bugs, GMP stamps), a tiny founder signature — is a signature like a corner pack-shot: it does NOT raise the stage. At LEAD scale, aggregate proof IS product-level work = product_aware ("50,000 five-star reviews" or "Featured in Vogue" as the headline is the "you've seen us everywhere" posture, presuming the product is already being evaluated). LEAD SCALE = the proof is the headline itself or the first item in reading order; sub-headline or smaller aggregate-proof strips do not raise the stage (tie -> lower).
- AUTHORITY vs DEFENSE: authority styling (doctor-formulated, founder signature or headshot, credentials, manufacturing heritage, a unique mechanism) is a sophistication/proof device — it raises to product_aware ONLY when deployed to DEFEND why THIS product beats alternatives. A founder/origin story that INTRODUCES why the product exists ("nothing helped my daughter's eczema, so I spent 3 years making this") is bridge work = solution_aware, even with a hero bottle and a signature. Founder content is product_aware only when it argues this product's superiority or handles objections about it.
- CATEGORY-NEGATION vs DIFFERENTIATION: positioning that explains what the product IS by contrast with a known category ("not a sleep pill", "no melatonin") is INTRODUCTION = solution_aware, even with a hero bottle. It becomes product-level differentiation (product_aware) only when it contrasts THIS product against rivals WITHIN its own category ("not all probiotics survive stomach acid — this one does"). Test: intra-category contrast ("this one" vs the others) = defense = product_aware; advocacy of the category itself = concept-selling = solution_aware.
- COUNTER-EXAMPLES (no prominent branded product): the same mechanism/category message ("not a sleep pill", "natural cortisol supplement") on a LIFESTYLE image with NO bottle and no brand/logo stays solution_aware. A PURE SYMPTOM visual (a 3 AM clock, an exhausted person) with NO text, mechanism, or product/brand is problem_aware.
- product-hero (branded product as the visual, little or no other message): the decisive floor governs — solution_aware by default, regardless of an accompanying problem or desired-state visual (a packshot merely asserts the product exists); rises to product_aware only with dominant product-level work; most_aware only when the LEAD is an explicit price/offer.
- before/after: if the transformation is ATTRIBUTED to an identifiable product in the LEAD or dominant message — a hero/co-hero branded pack in frame, OR the product/brand named in the lead text ("6 weeks on [Brand]") — product_aware (the transformation IS product-level proof for that product); attribution that appears only as a closing reveal in a narrative multi-panel follows the multi-panel rule instead. A corner-signature pack-shot or footer logo does not engage this branch: judge the dominant transformation message. With NO identifiable product at all: a visual transformation alone is a desired-outcome lead = solution_aware, and a mechanism / explanatory lead = solution_aware. (A transformation cannot be product_aware when no product is identifiable.)
- pure offer (discount / %-off / urgency / "back in stock" as the LEAD) = most_aware. OFFER PROMINENCE: an explicit promo trigger (SALE / %-off / promo code / BOGO / "back in stock" / a named sale event like "New Year's Sale") at BANNER SCALE makes the ad most_aware EVEN WHEN testimonial / product-proof elements are also present: an offer only does work on settled desire, so the proof is in service of conversion. BANNER SCALE = the offer block is NOT badge/sticker/footer-scale AND is set in type comparable to the main headline, occupies a band of roughly a quarter of the frame or more, or is the first substantial text block in reading order. A SMALL promo badge/sticker, or a thin full-width footer strip in small type (a free-shipping note, a discount code), is badge-scale and does NOT raise the stage — judge the dominant message. SCARCITY-AS-PROOF vs SCARCITY-AS-TRIGGER: "sold out 5x" / waitlist-size claims framed as popularity proof (no price, code, deadline, or stock-count pressure) are superiority proof = product_aware; scarcity is most_aware only when it pressures immediate action on settled desire ("only 200 left", "ends tonight"). A restock/availability LEAD ("back in stock", "restocked") remains most_aware — availability itself is the act-now trigger for settled desire. PRICE-ANCHORING / value-justification ("$1/day", "cheaper than your daily latte", cost-per-serving math) is objection-handling = product_aware, NOT most_aware. A hard CTA or a results-timeline selling merit is still NOT an offer.
- listicle / article-style headline: route by CONTENT — symptoms/signs/root-causes with no solution path ("5 signs your gut is damaged", "the real reason you're tired") = problem_aware (or unaware if pure curiosity with no felt problem); a category/ingredient/mechanism presented as the means to the result ("7 reasons doctors recommend magnesium") = solution_aware; THIS/named product as the subject ("7 reasons this supplement works") = product_aware; an offer-led list = most_aware.
- long advertorial / sales image: judge by the HEADLINE / lead, not the body.
- review / testimonial / UGC screenshot / fake-DM / iMessage / tweet / Reddit-thread creative: route by the substantive MESSAGE, not the screenshot format — pain/symptoms only = problem_aware; a category/ingredient/routine as the fix = solution_aware; the BRAND named as something already taken/evaluated = product_aware. EXCEPTIONS: a staged conversation that INTRODUCES the brand to the in-conversation recipient (problem -> "you NEED to try X" / "it's called X") is discovery/bridge work = solution_aware; an unnamed-"this" endorsement ("TikTok made me buy this", "this fixed my bloating" — no readable brand, generic packaging) = solution_aware; a footer logo, page name, or avatar handle alone does NOT count as the brand being named. Next to a prominent branded product, a testimonial counts as product-level work ONLY if its content endorses the product or its result AS SOMETHING ALREADY TAKEN/EVALUATED — a discovery-framed recommendation ("you NEED to try X", "it's called X") remains bridge work even beside the hero pack (the solution_aware floor holds), and a pain-only quote beside the hero bottle is problem agitation: the floor holds, but it does NOT rise to product_aware.
- blind hook (meme / relatable / emotional narrative naming a solution category or mechanism, with no identifiable product packaging and no brand presence beyond, at most, a footer/corner signature — a footer logo does NOT defeat this rule): solution_aware ONLY when the category/mechanism is dropped as unexplained shorthand relying on prior familiarity ("Probiotics", "cortisol reducer"). If the ad must TEACH the mechanism cold, or names it as the CULPRIT/root cause beneath a dominant symptom lead, the naming does not raise the stage = problem_aware (tie -> lower). A meme naming NO category and showing no product: route by content — relatable pain/symptom humor = problem_aware; an aspirational desired-RESULT meme ("me after 8 hours of ACTUAL sleep") = solution_aware; pure absurdist/identity humor with neither = unaware.
- hidden-product objection-handling / authority: product_aware only when the copy clearly presumes a specific product is ALREADY under evaluation — "this formula", "our product", "you've seen us", product-specific USP/proof, objection-handling, or intra-category comparison ("this one" vs the others). If the brand/product is hidden and the copy merely introduces credentials, an origin story, manufacturing claims, or a unique mechanism as the reason a solution works, that is proof/sophistication on a bridge = solution_aware. Authority does not create product awareness without a product-evaluation frame.
- comparison / us-vs-them table: product_aware when an identifiable product, brand, or "our formula" is compared against named OR unnamed/generic rivals (a greyed-out "Other gummies" / "Them" column with check-x marks). Category-vs-category or method comparisons with no specific product under evaluation = solution_aware; a table that only diagnoses symptoms/causes with no solution path = problem_aware.
- multi-panel / comic / carousel frame: the READING-ORDER lead (first panel / top-left) is the opening — judge by it. The FLOOR applies across the WHOLE frame (a hero/co-hero branded product in any panel sets the solution_aware minimum), but the RISE to product_aware is judged by the reading-order lead and dominant message — product-level work confined to a closing reveal panel does not flip a problem/story-led sequence. Judge hero/co-hero at PANEL scale here — the frame-share and reading-order clauses of the PROMINENT/SMALL definitions apply to single-frame layouts, not across a multi-panel grid; a pack that is the hero of a late panel still sets the floor. EXCEPTION — comparative gag formats (Drake-style reject/approve, expanding-brain ladders, tier lists): the panels form ONE comparison, not a narrative — judge the comparison as a whole (the brand ranked above rejected RIVAL PRODUCTS or within-category alternatives = product_aware; the brand ranked above a rejected CATEGORY it positions itself against ("melatonin" rejected, [Brand] approved) is category-negation in gag form = solution_aware, per CATEGORY-NEGATION; only categories/mechanisms ranked, no product = solution_aware).
- quiz / diagnosis lead: the quiz mechanic does not set awareness — route by what the quiz PRESUMES: a symptom/problem quiz ("Is your gut leaky? Take the quiz") = problem_aware; a result/category finder ("find the right electrolyte mix for you") = solution_aware; a personalization quiz whose OUTPUT is one of the brand's own products ("find YOUR [Brand] formula", "which [Brand] blend are you?") = product_aware — a generic category/result finder stays solution_aware even with the brand's pack in frame; a discount-led quiz = most_aware.
- textless / pure-aesthetic creative (product or food/beverage styling, a lifestyle flat-lay with NO headline, no claims, and no identifiable branded pack at hero/co-hero scale — a corner-signature pack or footer logo does NOT defeat this rule): sensory/appetite appeal presumes nothing — unaware. Beautiful styling is desire-CREATION, not desire-channeling. This rule governs only visuals that depict neither problem nor result: a textless visual depicting the PROBLEM itself (a 3 AM clock, an exhausted or distressed person) is problem_aware per COUNTER-EXAMPLES; one depicting a RESULT the viewer is presumed to already seek as relief or achievement (peaceful attainment of sleep, energy, a transformation) = solution_aware — for human subjects, distress/struggle = symptom (problem_aware), peaceful attainment of the sought state = result (solution_aware), tie -> lower. Generic indulgence is neither = unaware. An identifiable branded pack at hero/co-hero scale engages the decisive floor instead.
- ingredient callouts: annotation that EXPLAINS the formula ("magnesium for sleep, L-theanine for calm") is introduction work = solution_aware; ingredient claims EXPLICITLY framed against rivals in the product's own category ("no fillers — unlike most gummies", "ONLY 3 ingredients — most use 20") = differentiation = product_aware; a bare negation of an ingredient that DEFINES a contrasted category ("no melatonin", "no caffeine") is CATEGORY-NEGATION = solution_aware. A supplement-facts/label panel as the hero visual follows the floor + product-level-work rules.
- risk-reversal lead (money-back guarantee / free-trial as the HEADLINE): product_aware objection-handling, NOT most_aware — most_aware requires a price / discount / urgency / scarcity lead where desire is already settled."""
