-- Migration: Comic Video System Tables
-- Date: 2025-12-08
-- Purpose: Tables for comic panel video generation system
-- VERIFIED: No naming collisions with existing tables

-- ============================================================================
-- Comic Video Projects
-- Main project table storing comic grid, JSON, and status
-- ============================================================================
CREATE TABLE IF NOT EXISTS comic_video_projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    slug TEXT UNIQUE,

    -- Source files
    comic_grid_url TEXT NOT NULL,          -- URL to master comic image in storage
    comic_json JSONB NOT NULL,             -- Panel metadata from comic generator

    -- Parsed layout (from comic_json.layout_recommendation)
    layout JSONB,                          -- ComicLayout as JSON

    -- Output settings
    output_width INT DEFAULT 1080,
    output_height INT DEFAULT 1920,
    fps INT DEFAULT 30,

    -- Optional
    background_music_url TEXT,

    -- Status
    status TEXT DEFAULT 'draft',
    -- Values: draft, parsing, audio_generating, audio_ready, directing,
    --         ready_for_review, rendering, complete, failed
    error_message TEXT,

    -- Output
    final_video_url TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE comic_video_projects IS 'Comic video generation projects';
COMMENT ON COLUMN comic_video_projects.comic_grid_url IS 'URL to the master comic grid image (~4000x6000px)';
COMMENT ON COLUMN comic_video_projects.comic_json IS 'Full comic JSON with panels, layout_recommendation, visual_flow';
COMMENT ON COLUMN comic_video_projects.layout IS 'Parsed ComicLayout: grid dimensions, panel_cells mapping';
COMMENT ON COLUMN comic_video_projects.status IS 'Project lifecycle: draft → parsing → audio_generating → directing → rendering → complete';

-- Index for status queries
CREATE INDEX IF NOT EXISTS idx_comic_video_projects_status ON comic_video_projects(status);


-- ============================================================================
-- Comic Panel Audio
-- Audio file per panel (voiceover from ElevenLabs)
-- ============================================================================
CREATE TABLE IF NOT EXISTS comic_panel_audio (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES comic_video_projects(id) ON DELETE CASCADE,

    panel_number INT NOT NULL,             -- 1-indexed panel number
    audio_url TEXT NOT NULL,               -- Storage URL for audio file
    audio_filename TEXT NOT NULL,          -- Filename (e.g., '01_title.mp3')
    duration_ms INT NOT NULL,              -- Audio duration in milliseconds

    -- Voice settings used
    voice_id TEXT,                         -- ElevenLabs voice ID
    voice_name TEXT,                       -- Voice display name

    -- Source text
    text_content TEXT DEFAULT '',          -- Text that was spoken

    -- Approval
    is_approved BOOLEAN DEFAULT FALSE,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(project_id, panel_number)
);

COMMENT ON TABLE comic_panel_audio IS 'Audio files for each comic panel';
COMMENT ON COLUMN comic_panel_audio.panel_number IS '1-indexed panel number matching comic JSON';
COMMENT ON COLUMN comic_panel_audio.is_approved IS 'User has approved this audio for final render';

-- Index for project lookups
CREATE INDEX IF NOT EXISTS idx_comic_panel_audio_project ON comic_panel_audio(project_id);


-- ============================================================================
-- Comic Panel Instructions
-- Camera/effects instructions per panel (generated by director service)
-- ============================================================================
CREATE TABLE IF NOT EXISTS comic_panel_instructions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES comic_video_projects(id) ON DELETE CASCADE,

    panel_number INT NOT NULL,
    panel_type TEXT DEFAULT 'CONTENT',     -- TITLE, ACT X - CONTENT, OUTRO, etc.

    -- Duration
    duration_ms INT NOT NULL,

    -- From comic JSON
    header_text TEXT,
    dialogue TEXT,
    mood TEXT DEFAULT 'neutral',           -- PanelMood enum value

    -- Generated instructions (full PanelInstruction as JSON)
    camera_json JSONB NOT NULL,            -- PanelCamera
    effects_json JSONB NOT NULL,           -- PanelEffects
    transition_json JSONB NOT NULL,        -- PanelTransition

    -- Approval
    is_approved BOOLEAN DEFAULT FALSE,

    -- Preview
    preview_url TEXT,                      -- URL to preview video clip

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(project_id, panel_number)
);

COMMENT ON TABLE comic_panel_instructions IS 'Camera and effects instructions for each panel';
COMMENT ON COLUMN comic_panel_instructions.camera_json IS 'PanelCamera: zoom, pan, focus points, easing';
COMMENT ON COLUMN comic_panel_instructions.effects_json IS 'PanelEffects: ambient, triggered, color tint';
COMMENT ON COLUMN comic_panel_instructions.transition_json IS 'PanelTransition: type, duration, easing';
COMMENT ON COLUMN comic_panel_instructions.preview_url IS 'URL to preview video for this panel (before final render)';

-- Index for project lookups
CREATE INDEX IF NOT EXISTS idx_comic_panel_instructions_project ON comic_panel_instructions(project_id);


-- ============================================================================
-- Comic Render Jobs
-- Track render progress for panel previews and final video
-- ============================================================================
CREATE TABLE IF NOT EXISTS comic_render_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES comic_video_projects(id) ON DELETE CASCADE,

    -- Job type
    job_type TEXT NOT NULL,                -- 'panel_preview' or 'final_video'
    panel_number INT,                      -- For panel_preview jobs

    -- Status
    status TEXT DEFAULT 'queued',
    -- Values: queued, processing, complete, failed

    -- Progress (for final_video)
    current_panel INT DEFAULT 0,
    total_panels INT,

    -- Output
    output_url TEXT,
    error_message TEXT,

    -- Timestamps
    queued_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

COMMENT ON TABLE comic_render_jobs IS 'Render job queue for panel previews and final videos';
COMMENT ON COLUMN comic_render_jobs.job_type IS 'panel_preview (single panel) or final_video (full render)';

-- Index for status queries
CREATE INDEX IF NOT EXISTS idx_comic_render_jobs_status ON comic_render_jobs(status);
CREATE INDEX IF NOT EXISTS idx_comic_render_jobs_project ON comic_render_jobs(project_id);


-- ============================================================================
-- Updated timestamp trigger
-- ============================================================================
CREATE OR REPLACE FUNCTION update_comic_video_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to projects table
DROP TRIGGER IF EXISTS comic_video_projects_updated ON comic_video_projects;
CREATE TRIGGER comic_video_projects_updated
    BEFORE UPDATE ON comic_video_projects
    FOR EACH ROW
    EXECUTE FUNCTION update_comic_video_timestamp();

-- Apply to instructions table
DROP TRIGGER IF EXISTS comic_panel_instructions_updated ON comic_panel_instructions;
CREATE TRIGGER comic_panel_instructions_updated
    BEFORE UPDATE ON comic_panel_instructions
    FOR EACH ROW
    EXECUTE FUNCTION update_comic_video_timestamp();
