-- Add product_id and product_adaptation columns to video_analysis table
-- This enables multi-brand product-aware video analysis

-- Add product_id column (nullable, references products table)
ALTER TABLE video_analysis
ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES products(id) ON DELETE SET NULL;

-- Add product_adaptation column (JSONB for storing adaptation details)
ALTER TABLE video_analysis
ADD COLUMN IF NOT EXISTS product_adaptation JSONB;

-- Add index on product_id for faster queries
CREATE INDEX IF NOT EXISTS idx_video_analysis_product_id ON video_analysis(product_id);

-- Add index on post_id + product_id combination (for finding analyses by post and product)
CREATE INDEX IF NOT EXISTS idx_video_analysis_post_product ON video_analysis(post_id, product_id);

-- Add comment
COMMENT ON COLUMN video_analysis.product_id IS 'Product this analysis was generated for (optional)';
COMMENT ON COLUMN video_analysis.product_adaptation IS 'Product-specific adaptation ideas generated by AI';

-- Example product_adaptation structure:
-- {
--   "how_this_video_style_applies": "Explanation of how this viral pattern applies to the product",
--   "adaptation_ideas": ["Idea 1", "Idea 2", "Idea 3"],
--   "script_outline": "Detailed script outline adapted for the product",
--   "key_differences": "What needs to change from the original",
--   "target_audience_fit": "8/10 because...",
--   "estimated_production_difficulty": "medium|easy|hard",
--   "required_props_or_setup": ["Item 1", "Item 2"]
-- }
